name: shartflix
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  build_runner: ^2.6.0
  dio: ^5.8.0+1
  easy_localization: ^3.0.8
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^9.2.4
  get_it: ^8.0.3
  go_router: ^14.6.2
  json_annotation: ^4.9.0
  json_serializable: ^6.10.0
  image_picker: ^1.0.4
  equatable: ^2.0.5
  cached_network_image: ^3.3.1
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  fonts:
    - family: EuclidCircularA
      fonts:
        - asset: assets/fonts/Euclid Circular A Light.ttf
          weight: 300
        - asset: assets/fonts/Euclid Circular A Regular.ttf
          weight: 400
        - asset: assets/fonts/Euclid Circular A Medium.ttf
          weight: 500
        - asset: assets/fonts/Euclid Circular A SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Euclid Circular A Bold.ttf
          weight: 700
  
  assets:
    - assets/translations/
    - assets/lottie/
